### ISSUE TITLE
Markup for theorems

### ISSUE THREAD

**Issue by cben** [cben/mathdown#34]
Find and recommend some way to write theorems, lemmas etc. in MD and get them converted to `\begin{theorem}...` in latex.

Pandoc supposedly [added](https://groups.google.com/d/msg/pandoc-discuss/_e_g7O_cEEo/xY3k42n31xYJ) arbitrary `<div>` and `<span>` but I haven't been able to reproduce yet — probably need a newer version.

**Comment by anpc** [comment]
There is no consensus about theorem-like markup in markdown, only personal hacks here and there.  Since the value of this site is you're editing "standard" markdown you can export anywhere (at least to Pandoc), it's best for now to settle on what just works:

Just write `\begin{theorem}...\end{theorem}`!  Pandoc passes it on to the latex output as a raw block.  The obvious downside is that the content is not parsed as markdown - instead of `*emphasis*`, `* lists` etc. have to write `\emph{}`, `\begin{itemize} \item ...` etc.
A deeper problem is that it's entirely absent from HTML output :-(
- [ ] Figure out what can be done about HTML output.
- [ ] Turn on latex syntax highlight with \begin...\end.
- [ ] Support `\label` and `\ref`.
- [ ] Math-like preview of `\begin{theorem}` as bold **Theorem 3.** ?  Cf. what JaxEdit does.

**Comment by cben** [comment]
OTOH, https://github.com/jgm/pandocfilters/blob/master/examples/theorem.py

**Comment by cben** [comment]
Instiki has markdown syntax for theorem-like blocks:
https://golem.ph.utexas.edu/wiki/instiki/show/Theorems

Too ugly IMO.

**Comment by cben** [comment]
[CoffeeTeX](https://github.com/kasperpeulen/CoffeeTeX) supports unicode syntaxes like `⟦𝐓𝐡𝐞𝐨𝐫𝐞𝐦.  ...  ⟧` which is interesting but the use of math bold letters to denote the kind of environment offends my sensibilities.
However, I like CoffeeTeX overall (see #36) and wonder whether a markdownish variation of `⟦**Theorem**.  ...  ⟧` (not currently supported by CoffeeTex) would be a good idea.

As mentioned above, the deep blocker is easy export to supported formats.  At this stage (when don't even run my own export converter) I'd rather stick to source that works with existing tools (possibly with in-editor rendering — e.g. `\begin{theorem}` becoming **Theorem** — while still making the source editable, like I do for math.)

In the longer term, I should wait for scholdoc to choose & implement theorem syntax — listed as "Future plans (as of October 2014)" in http://scholarlymarkdown.com/Scholarly-Markdown-Guide.html#summary-of-new-features-in-scholarlymarkdown
